#!/bin/bash
# Author: Gang Cheng
# Date Created: 29.11.2021
# Decription: run command to check system status
# Date modified:29.11.2021
echo
echo "this script will run basic admin commands"

echo
top | head -10
echo
df -h
echo
w
echo
uptime
echo
iostat




