#!/bin/bash
# Author: Gang Cheng
# Date Created: 29.11.2021

count=100
	if [ $count -eq 100]
	then
	echo "count is 100"
	else
	echo "count is not 100"
	fi

clear

	if [ -e /home/gangch/error.txt ]
		then
		echo "file exists"
		else
		echo "file does not exist"
	fi
