#!/bin/bash
# Author:
# Time created:
# Description: $$ is the PID, $0 is the script file, $@ is the array of arguments, $# is number of argument



# Define variables

p=pwd
l=ls
wi=whoami
d=date
c=cal

echo "run variable tasks"
echo
echo $p
$l
$wi
$d
$c

